import Link from "next/link";
import Swarm from "@/components/Swarm";
import Pipeline from "@/components/Pipeline";
import Counter from "@/components/Counter";
import { CTA, Eyebrow } from "@/components/Chrome";
import { PROJECTS } from "@/lib/projects";
import { SITE, TESTIMONIALS } from "@/lib/site";

export default function Home() {
  const featured = ["vuemotion","vistacloud","malta-experience","delhi-o-delhi","novel-aquatech-portal","ninas-arts"]
    .map((s) => PROJECTS.find((p) => p.slug === s)!)
    .filter(Boolean);

  return (
    <>
      {/* ---------------- HERO ---------------- */}
      <header className="hero sec-dark">
        <div className="wrap hero-in">
          <Eyebrow>Kolkata · Sydney · Valletta · New York</Eyebrow>

          <h1 className="h1">
            One brief in.
            <em>A thousand sites out.</em>
          </h1>

          <p className="hero-sub">
            Anixsoft builds the software that builds software. Anix Forge takes a
            single business brief and generates thousands of genuinely different
            websites — no two from the same template. Try it on your own business
            below.
          </p>

          <Swarm count={12} />

          <div className="stat-row">
            <div className="stat">
              <b><Counter /></b>
              <span>sites generated by Forge</span>
            </div>
            <div className="stat">
              <b>11</b>
              <span>countries delivered to since 2015</span>
            </div>
            <div className="stat">
              <b>9 sec</b>
              <span>average build-and-deploy per site</span>
            </div>
          </div>
        </div>
      </header>

      {/* ---------------- SERVICES ---------------- */}
      <section className="sec sec-light">
        <div className="wrap">
          <Eyebrow>What we build</Eyebrow>
          <h2 className="h2">
            Anyone can generate a page. We build the systems underneath.
          </h2>
          <p className="lede">
            AI made simple websites cheap. It did not make payroll engines,
            civic complaint platforms or motion-analysis pipelines cheap.
            That is where we work.
          </p>

          <div className="grid-2">
            <div>
              <span className="kicker mono">AI &amp; automation</span>
              <h3>Generation systems</h3>
              <p>
                Python pipelines that produce content, layouts and deployable
                code at volume. Built for agencies, franchises and marketplaces
                that need hundreds of sites, not one.
              </p>
            </div>
            <div>
              <span className="kicker mono">Platforms</span>
              <h3>Business software</h3>
              <p>
                Payroll, expenses, membership, billing and operations tools.
                Multi-tenant, role-based, built to survive audits and grow with
                headcount.
              </p>
            </div>
            <div>
              <span className="kicker mono">Product</span>
              <h3>Web &amp; mobile apps</h3>
              <p>
                React and React Native front-ends on APIs we design ourselves.
                Shipped for restaurants in Sydney, tourism in Malta and
                manufacturers in India.
              </p>
            </div>
            <div>
              <span className="kicker mono">Applied AI</span>
              <h3>Model integration</h3>
              <p>
                Vision, document and language models wired into real workflows —
                with the evaluation, cost controls and fallbacks that keep them
                usable in production.
              </p>
            </div>
          </div>

          <div className="btn-row">
            <Link href="/services/" className="btn btn-dark">
              How we work
            </Link>
          </div>
        </div>
      </section>

      {/* ---------------- FORGE PIPELINE ---------------- */}
      <section className="sec sec-deep">
        <div className="wrap">
          <Eyebrow>Anix Forge</Eyebrow>
          <h2 className="h2">The pipeline behind the swarm</h2>
          <p className="lede">
            Six stages, fully parallelised. A thousand-site run finishes before a
            traditional agency has scheduled the kickoff call.
          </p>

          <Pipeline />

          <div className="btn-row">
            <Link href="/forge/" className="btn btn-brand">
              How Anix Forge works
            </Link>
            <Link href="/contact/" className="btn btn-ghost">
              Request a demo
            </Link>
          </div>
        </div>
      </section>

      {/* ---------------- WORK ---------------- */}
      <section className="sec sec-light">
        <div className="wrap">
          <Eyebrow>Selected work</Eyebrow>
          <h2 className="h2">Systems in production, not screenshots</h2>

          <div className="work-grid">
            {featured.map((p, idx) => (
              <Link
                href={`/work/${p.slug}/`}
                className="wcard"
                key={p.slug}
                style={{ animationDelay: `${idx * 60}ms` }}
              >
                <div className="wc-media">
                  {p.image ? (
                    <img src={p.image} alt={`${p.name} — screenshot`} loading="lazy" />
                  ) : (
                    <div className="wc-fallback"><span>{p.name}</span></div>
                  )}
                </div>
                <div className="wc-body">
                  <span className="tag mono">{p.category} · {p.country}</span>
                  <h3>{p.name}</h3>
                  <p>{p.summary}</p>
                  <div className="result">
                    <b>{p.metric}</b>
                    <span>{p.metricLabel}</span>
                  </div>
                </div>
              </Link>
            ))}
          </div>

          <div className="btn-row">
            <Link href="/work/" className="btn btn-dark">
              All case studies
            </Link>
          </div>
        </div>
      </section>

      {/* ---------------- GLOBAL PROOF ---------------- */}
      <section className="sec sec-dark">
        <div className="wrap">
          <Eyebrow>Where we work</Eyebrow>
          <h2 className="h2">Eleven countries. One team. Ten years.</h2>
          <p className="lede">
            We have been shipping across time zones since 2015 — long enough that
            our clients&apos; clients are now our clients.
          </p>

          <div className="pills">
            {SITE.countries.map((c) => (
              <span key={c}>{c}</span>
            ))}
          </div>

          <div className="quotes">
            {TESTIMONIALS.map((t) => (
              <blockquote className="quote" key={t.author}>
                <p>{t.quote}</p>
                <footer>
                  {t.author} — {t.where}
                </footer>
              </blockquote>
            ))}
          </div>
        </div>
      </section>

      <CTA />
    </>
  );
}
